[theme]
base = "dark"
primaryColor = "#4F8CC9"
backgroundColor = "#1E222A"
secondaryBackgroundColor = "#2B303C"
textColor = "#E2E8F0"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false